[sncast.sepolia]
account = "shadowswap"
url = "https://api.cartridge.gg/x/starknet/sepolia"
accounts-file = "/Users/ayushjangid/.starknet_accounts/starknet_open_zeppelin_accounts.json"

[sncast.default]
account = "shadowswap"
url = "https://api.cartridge.gg/x/starknet/sepolia"
accounts-file = "/Users/ayushjangid/.starknet_accounts/starknet_open_zeppelin_accounts.json"
