[package]
name = "shadow_swap"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.15.0"
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v1.0.0" }

[lib]

[[target.starknet-contract]]
sierra = true
casm = true
